### ISSUE TITLE
Request error: https://api.openai.com/v1/chat/completions: Connection Failed: Connect error

### ISSUE THREAD

**Issue by zhichonglyu** [openai-rs/gptpal#2]
Request error: https://api.openai.com/v1/chat/completions: Connection Failed: Connect error

**Comment by jiguantong** [comment]
Please set your proxy, for example:

![image](https://user-images.githubusercontent.com/27564714/230537184-738991a6-00d8-4295-9c61-8777b277fab0.png)

**Comment by zhichonglyu** [comment]
> Please set your proxy, for example:
> 
> ![image](https://user-images.githubusercontent.com/27564714/230537184-738991a6-00d8-4295-9c61-8777b277fab0.png)

Thanks,
